server:
  port: 8191

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atr
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver