server:
  port: 8191

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atr2?createDatabaseIfNotExist=true
    username: ahmed
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
        